### ISSUE TITLE
Two ads aren't being detected

### ISSUE THREAD

**Issue by gdi3d** [gdi3d/mute-spotify-ads-mac-osx#1]
I've found two ads that are not being detected by the script.

I'm investigating how to detect them to create a fix for those too.

**Comment by defser** [comment]
Create a database with flagged "songs" so that users can blacklist ads songs. Maybe even a online database so community can add blacklisted songs?

**Comment by gdi3d** [comment]
It's not necessary to have a db actually. The problem is that those type of ads don't show up in the event logs. I'm still debugging to know more.

**Comment by gdi3d** [comment]
There's no way to detect those Ads. The good thing is that they don't show too often so it's not a big problem
