### ISSUE TITLE
Enhancement: Play a selected Media File until spotify finishes its ads

### ISSUE THREAD

**Issue by Shabinder** [gdi3d/mute-spotify-ads-mac-osx#10]
As soon as you get event for spotify ads beginning , set spotify app's volume to 0 and play a media file [from users directory, ask user to pass an arg when he/she starts the script] as soon as you get event for a beginning of a new song , stop that media file and increase volume of spotify

**Comment by gdi3d** [comment]
Hey, thanks for the tip. This was something I wanted to do but I want to keep it simply for now.

I'm closing the ticket. Thanks again 👍🏻

**Comment by Shabinder** [comment]
Ohk as you see fit...
however, it is still a nice feature to have and I will like if you will reconsider it adding in the coming future.
Thanks for this script tho👍🏻
