### ISSUE TITLE
Better using automator than terminal

### ISSUE THREAD

**Issue by dinouse** [gdi3d/mute-spotify-ads-mac-osx#12]
I would like to recommend to use automator than terminal, because sometimes terminal would blocked the ads late. But for automator it would block the ads anytime.

**Comment by gdi3d** [comment]
Yeah, I tried at first but I couldn't make it work. I'll have to look it again and see if I can migrate it.

Thanks for your comment ;)

**Comment by hsl1** [comment]
hi, this script will work with the automator?

**Comment by gdi3d** [comment]
Yes, you could create an automator app and connect the script to it if you
want.
