### ISSUE TITLE
Trigger this script automatically on Spotify app launch

### ISSUE THREAD

**Issue by sankarsh98** [gdi3d/mute-spotify-ads-mac-osx#15]
Instead of manually running the script every time, is there a way to trigger the script while spotify application is opened/launched.

**Comment by gdi3d** [comment]
Hello Sankarsh98. Yes, it can be done by using **Automator** https://support.apple.com/guide/automator/welcome/mac

**Comment by sankarsh98** [comment]
Thanks! I will be checking that.
