### ISSUE TITLE
please help, when i copy and paste that it appeared this

### ISSUE THREAD

**Issue by msitinh** [gdi3d/mute-spotify-ads-mac-osx#16]
Macs-MacBook-Air:~ macairr$ mkdir -p ~/MuteSpotifyAds && curl https://raw.githubusercontent.com/gdi3d/mute-spotify-ads-mac-osx/master/NoAdsSpotify.sh > ~/MuteSpotifyAds/NoAdsSpotify.sh
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100  7240  100  7240    0     0  34835      0 --:--:-- --:--:-- --:--:-- 34975
Macs-MacBook-Air:~ macairr$ sh ~/MuteSpotifyAds/NoAdsSpotify.sh

Spotify Ads will be silenced while this program is running!. (This works ONLY with the Spotify App, not the web version)
This program was downloaded from https://gdi3d.github.io/mute-spotify-ads-mac-osx/ (check for documentation)

If the program is not working properly please open an issue at: https://github.com/gdi3d/mute-spotify-ads-mac-osx/issues/new

Press control+c to close this program or close the terminal window

log: PID not found for 'mediaremoted'
>>> ⛔️ 👎 Oops! Something failed and the program is not running. Please open a new issue at: https://github.com/gdi3d/mute-spotify-ads-mac-osx/issues/new and copy and paste the whole output of this window into so I can fix it.

**Comment by gdi3d** [comment]
Hello, I guess you're running a very old version of the mac operating system.

Can you run this command: `defaults read loginwindow SystemVersionStampAsString` in the terminal and paste the result here? It should display a number.

**Comment by gdi3d** [comment]
closed due to inactivity
