### ISSUE TITLE
automate

### ISSUE THREAD

**Issue by alesx2io** [gdi3d/mute-spotify-ads-mac-osx#18]
this script works perfectly, however I'd like a way to execute it automatically when Spotify gets opened, is there a way?

**Comment by shndowbots** [comment]
This probably shouldn't be put here because it's not an issue, but you may want to look into this [link](https://superuser.com/questions/756853/how-to-automate-shell-script-to-run-when-i-open-a-particular-app-in-osx).

**Comment by shndowbots** [comment]
You could also do something with automator, maybe have a quick action that launches Spotify and run a shell script.

**Comment by shndowbots** [comment]
Nevermind, the second comment I wrote was right. Use automaton. Here's an old issue regarding this. [Issue15](https://github.com/gdi3d/mute-spotify-ads-mac-osx/issues/15)

**Comment by gdi3d** [comment]
Hey @alesx2io, you can use **Automator** to do this. The link provided by @shndowbots (thanks btw), is a good way to get started, but you should also check out the documentation https://support.apple.com/guide/automator/welcome/mac
