### ISSUE TITLE
How to delete this file

### ISSUE THREAD

**Issue by v9pt** [gdi3d/mute-spotify-ads-mac-osx#19]
Where can i find the file i want to uninstall it

**Comment by gdi3d** [comment]
Hello, you have all the information available at https://gdi3d.github.io/mute-spotify-ads-mac-osx/

1. Go to your home folder (the one with the 🏠 icon) using the Finder
2. Make sure you’re not running the program (step 6 in the list above)
3. Find the folder called MuteSpotifyAds and delete it.
