### ISSUE TITLE
Issue for macos spotify

### ISSUE THREAD

**Issue by jgr124** [gdi3d/mute-spotify-ads-mac-osx#23]
doesnt work with muting ads on spotify, but it saysit sworking on the terminal. i refreshed the app, but still no use

**Comment by gdi3d** [comment]
Hey, allow me to ask a few questions to try to help you:

1. Are you using the desktop Spotify app, right?
2. Could you copy and paste the output of the console here after you run the script?
3. Can you tell me what version of osx are you running. You can check it out by running `defaults read loginwindow SystemVersionStampAsString` in the terminal. Then copy the result here

**Comment by gdi3d** [comment]
Close due to inactivity
