### ISSUE TITLE
about stats.txt , what is this ?

### ISSUE THREAD

**Issue by League2EB** [gdi3d/mute-spotify-ads-mac-osx#24]
first , Thank you for your brilliant idea

But I don't understand the purpose of stats.txt
It always makes

What is it used for? 
thx all 
```shell
# create stats file
if ! test -f "stats.txt"; then
    echo 0 > stats.txt
fi
```

**Comment by gdi3d** [comment]
Hey, thanks for your kind words.

`stats.txt` is the file used to store the amount of minutes of ads blocked. This way the script can show you how many minutes/hours of ads have been muted.

If you deleted the file, next time you run the script it will be created again. But, of course, you will loose that information.
