### ISSUE TITLE
The Spotify mute isn't working

### ISSUE THREAD

**Issue by jimnyo** [gdi3d/mute-spotify-ads-mac-osx#26]
Can you help?

**Comment by jimnyo** [comment]
And yes, I'm using the Mac Desktop app, not the web app. It was working last week and now it doesn't seem to be working.

**Comment by gdi3d** [comment]
Hey!, sure, can you share the ouput of the script after you execute it?, also, do you see any messages when you start playing a song?

**Comment by jimnyo** [comment]
this is a copy of the entirety--script included--and no, i don't see any mesages when i start playing a song:

Last login: Mon Jul  4 20:52:10 on ttys000
yo@MacBook-Pro ~ % mkdir -p ~/MuteSpotifyAds && curl https://raw.githubusercontent.com/gdi3d/mute-spotify-ads-mac-osx/master/NoAdsSpotify.sh > ~/MuteSpotifyAds/NoAdsSpotify.sh

  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100  8710  100  8710    0     0  44226      0 --:--:-- --:--:-- --:--:-- 45602
yo@MacBook-Pro ~ % sh ~/MuteSpotifyAds/NoAdsSpotify.sh


Spotify Ads will be silenced while this program is running!. (This works ONLY with the Spotify App, not the web version)
This program was downloaded from https://gdi3d.github.io/mute-spotify-ads-mac-osx/ (check for documentation)

If the program is not working properly please open an issue at: https://github.com/gdi3d/mute-spotify-ads-mac-osx/issues/new

Press control+c to close this program or close the terminal window

>> 🔈 Songs are playing 😀🕺💃. Audio back to normal

**Comment by jimnyo** [comment]
So weird, it's working now...

**Comment by jimnyo** [comment]
Oh WAIT!! I just remembered, it doesn't work if I use the Spotify app to play on the Alexa, is that correct??

**Comment by gdi3d** [comment]
As far as I know (I don't own an Alexa), it's not your computer playing the songs, it's Alexa. This means that all the downloading and playing is happing on the Alexa device.

You can test it by using Spotify with your headphones/speakers/bluetooth device and you'll see the script working properly.

And if you see the output that you just paste, it clearly says:

`🔈 Songs are playing 😀🕺💃. Audio back to normal`

This means that the script has detected a song playing and that it's working properly.

**Comment by gdi3d** [comment]
You can close the ticket if the test I mentioned before works ok

**Comment by gdi3d** [comment]
Closing ticket due to inactivity
