### ISSUE TITLE
it dose not work when you are using HDMI speakers

### ISSUE THREAD

**Issue by moshtaghi** [gdi3d/mute-spotify-ads-mac-osx#3]

**Comment by gdi3d** [comment]
mmm good observation. I will work on a fix for this.

Thanks for reporting

**Comment by gdi3d** [comment]
Hey, I've just pushed a new version to support HDMI by lowering the volume on Spotify app in that case. Could you test it and tell me if works ok for you?

You need to run it like this `sh ~/MuteSpotifyAds/NoAdsSpotify.sh hdmi`
