### ISSUE TITLE
Error when run script

### ISSUE THREAD

**Issue by ChemaBautista** [gdi3d/mute-spotify-ads-mac-osx#30]
ej:
sh ~/MuteSpotifyAds/NoAdsSpotify.sh
return: 
unknown option: /Users/ch3ma/MuteSpotifyAds/NoAdsSpotify.sd

Tanks.

**Comment by gdi3d** [comment]
Hey, can you provide a little more information?

1. Did you installed the script as the documentation indicates https://gdi3d.github.io/mute-spotify-ads-mac-osx/ ?
2. What version of OSX are you running?
3. Can you check that you have the command `log` on your system by trying to run it in the terminal?
4. Why does it says: unknown option: /Users/ch3ma/MuteSpotifyAds/**NoAdsSpotify.sd** There no .sd file at all?

**Comment by gdi3d** [comment]
Closing ticket due to inactivity
