### ISSUE TITLE
Spotify ads playing after MacOS Ventura 13.0 update

### ISSUE THREAD

**Issue by ed97m** [gdi3d/mute-spotify-ads-mac-osx#31]
Ads now play on Spotify, this started after the most recent MacOS update. 13.0 Ventura, I really like using this script. Thanks for making it :)

**Comment by ed97m** [comment]
More details

The ads run like if the script were not to be running, despite being installed on and running. There are no errors on the terminal. See attached screenshot. 

![Screenshot 2022-10-27 at 12 21 13](https://user-images.githubusercontent.com/116829710/198345210-d10fc5e9-d026-4bdd-836a-2c86afcadf5c.jpg)

**Comment by ed97m** [comment]
More information. The terminal information does not display any errors, even when reinstalling and running the script the ads play.
![Screenshot 2022-10-27 at 12 22 52](https://user-images.githubusercontent.com/116829710/198345516-93765c67-078e-4f51-b176-fbb9b063c1c7.jpg)

See screenshot below

**Comment by gdi3d** [comment]
Hey, I'm not running Ventura right now. You can help me debug it, but it's gonna be tricky.

If you want, try the following. Run this on your terminal with Spotify running:

```
log stream --process="mediaremoted" --predicate='eventMessage contains[cd] "spotify.client"' 
```

And try to send me the output generated at the time an AD shows up so I can see if anything has changed.

This is kind of the **core** of the whole script. It reads the events of Spotify and you can see what song is playing, in case of the ads, the albumName property returns empty and thats when I silence the app.

I'm not planning to upgrade to Ventura until December, sorry :(

**Comment by Timekeeper0001** [comment]
Hi @gdi3d 
I tried to attach the output from terminal whilst the ads are running.  Not sure if this was the attached properly

[spotify ads ventura.txt](https://github.com/gdi3d/mute-spotify-ads-mac-osx/files/9896585/spotify.ads.ventura.txt)

**Comment by gdi3d** [comment]
@Timekeeper0001 Hey, it worked fine. But I need a little more info.

Try the following:

1. Run the same command again
2. Play a song for 4 or 5 seconds and pause it.
3. Copy and paste the log into the ticket

I belive this new version of OSX might be hidding the information needed for the script to work.

**Comment by Timekeeper0001** [comment]
Hi @gdi3d 
Ran this 1 song for 4 seconds and stopped it.  Had the spotify mute command in one terminal window.  And the debugging command in another terminal window

[spotify ads ventura2.txt](https://github.com/gdi3d/mute-spotify-ads-mac-osx/files/9900198/spotify.ads.ventura2.txt)

**Comment by gdi3d** [comment]
It looks like the log tool is not longer showing the information needed for the script to work. Maybe there's some extra config that could be added to the command to make it visible again.

I will be looking into this once I've updated to Ventura on December, and report any news in this ticket.

**Comment by Timekeeper0001** [comment]
@gdi3d 
Thank you for your effort my friend.    And if you cant get it resolved in the future, it was really good while it lasted.   Though Ill keep my fingers crossed because the ads are awful lol.  :)

**Comment by dlijavetzky** [comment]
Hi @gdi3d 
Thanks for the info and hope you can fix it soon!!!

**Comment by david-mccullars** [comment]
I dug into this a bit and saw that the album information is no longer being displayed. Without this the `AD_REG` and `SONG_REG` won't work. Instead of album I'm seeing `<<private>>`.

Fortunately, I found [this link](https://georgegarside.com/blog/macos/sierra-console-private/)  to be super helpful, and I believe it **solves the problem**. By installing the [enable-unified-log-private-data profile](https://georgegarside.com/blog/macos/sierra-console-private/enable-unified-log-private-data.mobileconfig) I started seeing the private data, including `album`.

**Comment by gdi3d** [comment]
Hey @david-mccullars , thanks for sharing!. 

I saw the same post a few days ago but I didn't have the time to test and research it.

I'm not too happy with the solution, since it requieres a certain level of knowledge and most of the user of the script are just regular user.  

I'm currently testing other methods but no luck so far.

I'll keep this issue updated with any new findings and/or solutions.

**Comment by gdi3d** [comment]
I think I've a found a way 💪💪💪

I will be testing it the coming days, keep fingers cross everyone!

**Comment by gdi3d** [comment]
I've found a solution to fix the problem. It doesn't require any extra software to be installed.

I'll be testing it for a few days to make sure everything works ok before rolling the update.

The only drawback is that now it will take between 1 and 2 seconds to detect the ad/song and update the volume to the correct level.

**Comment by bbbco** [comment]
Since this is a Mac only version, you could consider using oascript to detect the ads using the following check 

```
 osascript -e 'tell application "Spotify" to get spotify url of current track'
```

if ":ad:" is in the result, an ad is being played.

**Comment by gdi3d** [comment]
> Since this is a Mac only version, you could consider using oascript to detect the ads using the following check
> 
> ```
>  osascript -e 'tell application "Spotify" to get spotify url of current track'
> ```
> 
> if ":ad:" is in the result, an ad is being played.

🤯🤯🤯🤯🤯🤯🤯🤯🤯 AWESOME!!!

**Comment by bbbco** [comment]
I know ;)

I've got a crude Applescript that does this. Yours is much more polished.

**Comment by gdi3d** [comment]
I've found the original docs for this on Spotify dev page (only available on wayback machine now https://web.archive.org/web/20170913123237/https://developer.spotify.com/applescript-api/). 

I wasn't aware you had access to this using osascript 🙃.

I will give you credits on the commit and the posts announcing the version ;)

Can I post your twitter handle to give you credit?

**Comment by bbbco** [comment]
Sure, no problem! @bbbco is my handle here and on Twitter

**Comment by gdi3d** [comment]
The script is almost ready. I'll be launching the update on the weekend 🚀😀

**Comment by gdi3d** [comment]
New version launched!
