### ISSUE TITLE
Not muting

### ISSUE THREAD

**Issue by mrwa10** [gdi3d/mute-spotify-ads-mac-osx#34]
I have been using mute-spotify-ads on my mac-osx and it has worked but now it stopped working. Ads are playing as if the program were not running.

MacOS Monterey 12.6.1 (21G217)

Spotify for macOS (Intel)
1.1.67.586.gbb5ef64e

Would be glad if this helps getting the program better.

Cheers!

**Comment by gdi3d** [comment]
Hey, according to my investigations I think this might be related with #31 . 

Maybe Spotify has started to hide the information needed to mute the ads and it's not directly related to the new Ventura version.

I'll close this ticket since it's probably the same error.

**Comment by mrwa10** [comment]
Ok, thanks! And thank for creating the script!
All the best!
