### ISSUE TITLE
Latest update makes my fan go wild

### ISSUE THREAD

**Issue by jorondo1** [gdi3d/mute-spotify-ads-mac-osx#36]
Hi,
the latest update seems to have fixed a few issues I had (some types of ads were not being detected, and the program did not always start). However, since then, my computer fan goes ballistic when running the program, even when no other app (except spotify) are open. Spotify alone without the muter does not cause this problem. 

The header of my Terminal window is constantly switching between "sleep" and "cut" while an add is running, and between "sleep", "cut" and "osascript" when music is playing, which it did not before the update... there might be something there?&

Running on 10.14.6. Weirdly, no process seems to gobble up the CPU when this happens, but it is on average a lot higher when the program is running.

Any idea what could be causing this?

**Comment by gdi3d** [comment]
I've tested the new version for quite a few days now and didn't notice any peak on CPU usage.

You can try a few things:

1. Using activity monitor find the bash process that's running the script and see how much CPU is using when running (in my case is around (0,3/0,5%)
2. Edit the file, the line 62 `INTERVAL_CHECK_TIME_SEC=0.5` and change that number to 1 or 2 (you'll hear the first second or two of and ad in this case)

I'm currently running Ventura 13.0.1

If nothing works I can point you to the older version of the script.

**Comment by gdi3d** [comment]
Closing ticket due to inactivity
