### ISSUE TITLE
Guard auto-update from Github

### ISSUE THREAD

**Issue by pronebird** [gdi3d/mute-spotify-ads-mac-osx#39]
Amazing script. Thanks for saving me a million hours on stupid ads. Would it be possible to guard auto-update behind some flag?

**Comment by gdi3d** [comment]
Hi!, thanks for your kind words. Can I ask why would you need/want this? I don't push new versions that often.

**Comment by pronebird** [comment]
Security measure on my side. I prefer to update manually and inspect all scripts I execute on my computer.

**Comment by derkommutator** [comment]
If you manually inspect all scripts you execute, you have no doubt already found that it's trivial to disable the auto-update if you wish.

**Comment by gdi3d** [comment]
@pronebird By default the script won't auto-update itself (default option is No if you hit enter), but I guess I could add a flag for it or a countdown to skip the autoupdate if you don't interact choose an option.

**Comment by gdi3d** [comment]
@pronebird Hey but the more I think about it, the less sense it makes. The fact that you can choose **No** when an update it's available solves the issue from my perspective.

If you're worried about bad code being injected, then you should _freeze_ the code yourself by removing the auto-update code from line 6 to 32.

**Comment by pronebird** [comment]
@gdi3d precisely what I did. I'd appreciate if the script didn't call home but I can certainly remove those lines manually each time I update the script, which is hopefully not often.
