### ISSUE TITLE
Unexpected BEEP when ad is sensed

### ISSUE THREAD

**Issue by blakenan-bellese** [gdi3d/mute-spotify-ads-mac-osx#6]
I'm not 100% sure this is behavior due to the script, but I get a loud system beep whenever an ad is sensed.  The ad is muted and unmuted when song is detected, so that is working well.  Just the beep is a bit jarring.  Feel free to close if this is not caused by script.  I'm happy to help debug/test.

P.S. - Thanks for sharing the script.  Love it.

**Comment by gdi3d** [comment]
Hey, thanks for reporting. I think your problem resides on the configuration of your terminal window.

Open the terminal app and go to **Preferences > Profiles > Advanced** and uncheck the **Audible Bell** option.

The script doesn't generate any audio alerts so it has to be terminal. Check it out and let me know if that worked so I can go ahead and close the issue.

**Comment by blakenan-bellese** [comment]
Thanks for the feedback, this fixed my problem.   I had tried this once, but I'm a newb with iTerm2 so I guess I did it wrong. Your suggestion promoted me try again.  No more beep now.    Appreciate the help and sorry for the newb noise.

**Comment by blakenan-bellese** [comment]
Here's the cause of my issue, unrelated to the script: https://gitlab.com/gnachman/iterm2/-/issues/7964#:~:text=Linked%20issues&text=The%20simplest%20fix%20is%20to,Save%20the%20window%20arrangement.

**Comment by gdi3d** [comment]
Great to hear to you solved it. Thanks for contributing 😃
