### ISSUE TITLE
Problem in Installing Ad-Silencer

### ISSUE THREAD

**Issue by harsh778** [gdi3d/mute-spotify-ads-mac-osx#9]
Hi! First of all great work on this project. 
I was trying to install it using terminal but unfortunately I am encountering this error.
Please refer to the attached screenshot and help me fix the error!
Thanks in advance!
![Screen Shot 2021-04-03 at 8 46 03 PM](https://user-images.githubusercontent.com/51576476/113482763-b7e68600-94bd-11eb-8f4d-9887dab2a1be.png)

**Comment by gdi3d** [comment]
Can you run the following command in your terminal and tell me the output

`defaults read loginwindow SystemVersionStampAsString`

This will tell you the OSX version that you're running

**Comment by harsh778** [comment]
The version my mac is running is 10.12.6
![Screen Shot 2021-04-04 at 4 52 01 PM](https://user-images.githubusercontent.com/51576476/113507099-241cc480-9566-11eb-8814-8daa7159ad5b.png)

**Comment by gdi3d** [comment]
I'll need to check the documentation for that version before I can try to fix it. Thanks

**Comment by harsh778** [comment]
Oh sure, thanks:)

**Comment by gdi3d** [comment]
Please try the following to see if it works. It's not going to be very performant and it will use more CPU than the original but it will work.

Edit the file and replace the line #91:

`log stream --process="mediaremoted" --type="log" --color="none" --style="compact" | \`

to this:

`log stream --type="log" --color="none" --style="compact" | \`

This change will cause the script to go trough all the messages, causing more CPU usage.

I can't find why the process **mediaremoted** is not present in your version yet. But this will be only workaround in case I don't find what happend to **mediaremoted**

**Comment by harsh778** [comment]
Alright. So, I changed the line 91 of NoAdsSpotify.sh as told. I ran the program again from the terminal. This time, I face this error. 
![Screen Shot 2021-04-05 at 11 11 07 AM](https://user-images.githubusercontent.com/51576476/113541382-bb822600-95ff-11eb-96a5-2f17057a5a6c.png)

**Comment by gdi3d** [comment]
Try this:

`log stream --type="log" --style="syslog" | \`

**Comment by harsh778** [comment]
It seems to work this time because I didn't get any error. However, the ads still don't stop. I had the terminal running this program open and also the NoAdsSpotify.sh file (just in case). 
![Screen Shot 2021-04-05 at 4 39 45 PM](https://user-images.githubusercontent.com/51576476/113568182-aa500e00-962d-11eb-9b44-45ac4c39643f.png)

**Comment by gdi3d** [comment]
That's strange. I test that and works fine. Are you using HDMI speakers?

**Comment by harsh778** [comment]
Nope, I ain't using the HDMI speakers. For the program to work A-OK, I only need to run `sh ~/MuteSpotifyAds/NoAdsSpotify.sh` in the terminal right? Anything else needs to be done too?

**Comment by gdi3d** [comment]
Yes. Are you using the Spotify app, right? or are you using the web ?

**Comment by harsh778** [comment]
Yes, I am using the installable app.

**Comment by gdi3d** [comment]
Sorry, I don't know why it's not working then. Probably the logs are not working in the same way that they do on later versions of the OS.

I can't do anything more at this point

**Comment by harsh778** [comment]
Oh alrighty. Anyways, thanks a lot for all the help and prompt responses :)

**Comment by gdi3d** [comment]
Try this before I close the ticket:

- Run the script
- Play a song on Spotify. If it's working a message should appear saying: 🔈 Songs are playing 😀🕺💃. Audio back to normal

**Comment by harsh778** [comment]
No luck! No such message appears. 
Maybe, I will try updating the version of my mac and try again later some time. 
Thanks, once again!

**Comment by gdi3d** [comment]
Sorry I couldn't help you. Thanks for your support anyways.
Closing the ticket
